# Generated by Django 4.1.3 on 2022-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Familiares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("parentezco", models.CharField(max_length=40)),
                ("edad", models.IntegerField()),
                ("cumpleaños", models.DateField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(name="Amigos",),
    ]
